### ISSUE TITLE
FR5: Themes

### ISSUE THREAD

**Issue by rmoussa09** [WSU-4110/WellOff#10]
|FR5: Themes|
|---|
|**Goal**: Change the display settings between light mode or dark mode.
**Stakeholders:** Customers|
| **Description:** The user will have the option in settings to set their preference of display settings between light and dark mode. Default option upon first launch will be in light mode. |
| **Origin:**  Based on group concept discussion during the first team meeting 9/10.
| **Version:** 1.0  |
|**Date:** 09/22/2022
|  **Priority:** 5 |

**Comment by FredddyAdu** [comment]
Never implemented
