### ISSUE TITLE
FR12: Smart Notifications - Movement Detection: Idle

### ISSUE THREAD

**Issue by rmkatbey** [WSU-4110/WellOff#12]
|FR12: Smart Notifications - Movement Detection: Idle|
|---|
|**Goal**: Send notification when the user has been idle for X amount of hours.
**Stakeholders:** Customers|
|**Description:** Uses data pull to determine user’s movement, sends notification to user to get up when user has been idle for x amount of hours.|
| **Origin:** Based on group concept discussion during the first team meeting 9/10|
| **Version:** 1.0  |
|**Date:** 09/27/2022
|  **Priority:** 1 |

**Comment by FredddyAdu** [comment]
Smart notifcations were not implemented
