### ISSUE TITLE
FR13: Enable Smart Notifications

### ISSUE THREAD

**Issue by rmkatbey** [WSU-4110/WellOff#13]
|FR13: Enable Smart Notifications|
|---|
|**Goal**:  Feature that allows user to enable notifications.
**Stakeholders:** Customers|
|**Description:** Feature will allow users to enable which notifications they’d like to receive.|
| **Origin:** Based on group concept discussion during the first team meeting 9/10|
| **Version:** 1.0  |
|**Date:** 09/27/2022
|  **Priority:** 1 |

**Comment by FredddyAdu** [comment]
Never implemented
