### ISSUE TITLE
FR14: Smart Notifications - Bedtime

### ISSUE THREAD

**Issue by rmkatbey** [WSU-4110/WellOff#14]
|FR14: Smart Notifications - Bedtime|
|---|
|**Goal**:  Send notification recommending user to go to sleep.
**Stakeholders:** Customers|
|**Description:** Notifies the user to go to sleep at time the user selects from the Enable Notifications feature|
| **Origin:** Based on group concept discussion during the first team meeting 9/10|
| **Version:** 1.0  |
|**Date:** 09/27/2022
|  **Priority:** 1 |

**Comment by FredddyAdu** [comment]
Smart notifications was not implemented
