### ISSUE TITLE
FR10: Permission Settings

### ISSUE THREAD

**Issue by rmoussa09** [WSU-4110/WellOff#15]
|FR10: Permission Settings|
|---|
|**Goal**: The user can turn on permission settings (notifications) in case they forgot.
**Stakeholders:** Customers|
| **Description:** If denied permission of notifications on first launch, the user will have the option in settings to turn on their permission settings or keep off in the settings.
| **Origin:**  Based on group concept discussion during the first team meeting 9/10.
| **Version:** 1.0  |
|**Date:** 09/22/2022
|  **Priority:** 4 |

**Comment by commandobox** [comment]
Permissions are having issues as we cannot get the API to function correctly. We will probably have to move to a dummy API with some constants.

**Comment by commandobox** [comment]
@rmkatbey please put your firebase findings here and close with comment.

**Comment by FredddyAdu** [comment]
Firebase does not ask for persmission but google fit does and we took care of that
