### ISSUE TITLE
FR11: Admin Panel

### ISSUE THREAD

**Issue by rmoussa09** [WSU-4110/WellOff#16]
|FR11: Admin Panel|
|---|
|**Goal**: Create an admin panel to update maintenance of the application.
**Stakeholders:** Customers|
| **Description:** The user will have an admin panel to reach out for any concerns or issues regarding the application, and reconnect to the Apple Health application if needed.
| **Origin:**  Based on group concept discussion during the first team meeting 9/10.
| **Version:** 1.0  |
|**Date:** 09/22/2022
|  **Priority:** 3 |

**Comment by FredddyAdu** [comment]
Never implemented
