### ISSUE TITLE
FR14: Profile to Phone Integration

### ISSUE THREAD

**Issue by rmoussa09** [WSU-4110/WellOff#19]
|FR14: Profile to Phone Integration|
|---|
|**Goal**: The user’s profile data is saved to their phone upon reopening the app.
**Stakeholders:** Customers|
| **Description:** When closing the application, the user’s data will be saved in our database to ensure the same profile is shown upon the next startup. |
| **Origin:** Based on group concept discussion during the first team meeting 9/10.|
| **Version:** 1.0  |
|**Date:** 09/22/2019
|  **Priority:** 1 |

**Comment by FredddyAdu** [comment]
Data is stored within firebase database when working
