### ISSUE TITLE
FR2. Semi-Manual Data Pull (App Opening)

### ISSUE THREAD

**Issue by commandobox** [WSU-4110/WellOff#2]
|FR2.  Semi-Manual Data Pull (App Opening)
|---|
|**Goal**: Pull health data on app launch.
**Stakeholders:** Customers|
| **Description:** When the user launches the app, update the local data for the app. |
| **Origin:** Based on group concept discussion during the first team meeting 9/10.|
| **Version:** 1.0  |  
|**Date:** 09/21/2022  
|  **Priority:** 1 |

**Comment by FredddyAdu** [comment]
User has the ability to change goals and local data when necessary
