### ISSUE TITLE
FR3. Smart Reminders - Background Worker

### ISSUE THREAD

**Issue by commandobox** [WSU-4110/WellOff#3]
|FR3. Smart Reminders - Background Worker|
|---|
|**Goal**: Create some sort of background worker for FR1. to interact with for notification display.
**Stakeholders:** Customers|
| **Description:** The background worker will be in an idle state until it receives an invoke/interrupt to display a notification to the end user. |
| **Origin:** Based on group concept discussion during the first team meeting 9/10. |
| **Version:** 1.0  |  
|**Date:** 09/21/2022  
|  **Priority:** 1 |

**Comment by FredddyAdu** [comment]
Never implemented
