### ISSUE TITLE
FR4: Smart Notifications - Messages

### ISSUE THREAD

**Issue by commandobox** [WSU-4110/WellOff#4]
|FR4: Smart Notifications - Messages|
|---|
|**Goal**: When alerting the user about their personal goals, give a randomized message.
**Stakeholders:** Customers|
| **Description:** For each goal, there will be a set of predefined notification messages that can be interchanged out so as to not get stale. These messages can be similar to “Hey u didn’t close the circle yesterday. Let’s close it today!” |
| **Origin:** Based on group concept discussion during the first team meeting 9/10. |
| **Version:** 1.0  |  
|**Date:** 09/21/2022  
|  **Priority:** 1 |

**Comment by FredddyAdu** [comment]
Never implemented
