### ISSUE TITLE
NFR1: Permissions To Access Necessary Data

### ISSUE THREAD

**Issue by rifrod** [WSU-4110/WellOff#5]
|NFR1: Permissions To Access Necessary Data|
|---|
|**Goal**: The user gets prompted to allow access to different kinds of data when they first sign up for the app.
**Stakeholders:** Customers|
| **Description:** To be able to pull data from different apps such as the health app and the fitness app, the user will get prompted to give permission for the app to be able to access that data to be able to accurately help the user. |
| **Origin:** Based on group concept discussion during the first team meeting 9/10.|
| **Version:** 1.0  |
|**Date:** 09/22/2022
|  **Priority:** 1 |

**Comment by FredddyAdu** [comment]
Never implemented
