### ISSUE TITLE
NFR2: Silence App At Night

### ISSUE THREAD

**Issue by rifrod** [WSU-4110/WellOff#6]
|NFR2: Silence App At Night|
|---|
|**Goal**: The app goes to silent mode at night when the user is sleeping (at least 8 hours).
**Stakeholders:** Customers|
| **Description:** By default the app will enter silent mode when the user is sleeping so as to not wake the user or to keep them from sleeping by sending constant notifications. |
| **Origin:** Based on group concept discussion during the first team meeting 9/10.|
| **Version:** 1.0  |
|**Date:** 09/22/2022
|  **Priority:** 3 |

**Comment by FredddyAdu** [comment]
Never implemented
