### ISSUE TITLE
FR20: Two Factor Authentication

### ISSUE THREAD

**Issue by rifrod** [WSU-4110/WellOff#7]
|FR20: Two Factor Authentication|
|---|
|**Goal**: The user has to use two factor authentication to sign into the app every 3 to 4 weeks.|
**Stakeholders:** Customers|
| **Description:** For the purpose of keeping the user and their information secure the user will be asked to sign in using two factor authentication as it immediately neutralizes the risks associated with hacked passwords. |
| **Origin:** Based on group concept discussion during the first team meeting 9/10.|
| **Version:** 1.0  |
|**Date:** 09/22/2022
|  **Priority:** 4 |

**Comment by FredddyAdu** [comment]
Never implemented
